language: go

go:
  - "1.14"
  - master

before_install:
  - go get -u github.com/marthjod/bm/...
  - go get -u github.com/golang/lint/golint
  - go get -u github.com/kisielk/errcheck
  - go get -u honnef.co/go/tools/cmd/staticcheck

script:
  - make vet
  - make lint
  - make errcheck
  - make staticcheck
  - make test
